---
# Global configuration for claude-code-vm deployment
# These can be overridden via command line: -e "variable_name=value"

# === Connection Defaults (No hardcoded values - must be provided) ===
# These MUST be provided via command line or environment variables:
# -e "vm_host=192.168.1.111 vm_user=root target_vm_user=username"
vm_host: "{{ vm_host | mandatory }}"
vm_user: "{{ vm_user | default('root') }}"
vm_ssh_key: "{{ vm_ssh_key | default('~/.ssh/id_rsa') }}"
target_vm_user: "{{ target_vm_user | mandatory }}"

# === Advanced Authentication Options ===
# Connect directly as target user instead of using become (more secure)
connect_as_target_user: "{{ connect_as_target_user | default(false) }}"

# Target user specific SSH key (if different from vm_ssh_key)
target_user_ssh_key: "{{ target_user_ssh_key | default(vm_ssh_key) }}"

# Password authentication (if SSH keys not available)
use_ssh_password: "{{ use_ssh_password | default(false) }}"
ssh_password: "{{ ssh_password | default('') }}"

# Sudo password (if required for privilege escalation)
use_become_password: "{{ use_become_password | default(false) }}"
become_password: "{{ become_password | default('') }}"

# === Target Configuration ===
target_user: "{{ target_vm_user }}"

# Dynamic connection configuration based on authentication method
effective_ansible_user: "{{ target_vm_user if connect_as_target_user else vm_user }}"
effective_ssh_key: "{{ target_user_ssh_key if connect_as_target_user else vm_ssh_key }}"
effective_become: "{{ not connect_as_target_user }}"
target_user_home: "/home/{{ target_user }}"

# === Deployment Paths (Configurable) ===
# Remote directory where all deployment artifacts are stored
deployment_base_dir: "/home/{{ target_user }}/.claude-code-vm"
scripts_dir: "{{ deployment_base_dir }}/scripts"
config_dir: "{{ deployment_base_dir }}/config"
logs_dir: "{{ deployment_base_dir }}/logs"
temp_dir: "{{ deployment_base_dir }}/tmp"

# === MCP Configuration Paths ===
# These can be overridden via -e custom_env_file=/path/to/.env
mcp_env_file: "{{ custom_env_file | default(inventory_dir + '/.env') }}"
mcp_servers_config: "{{ custom_mcp_file | default(inventory_dir + '/mcp-servers.json') }}"

# === Component Versions ===
nodejs_version: "22"
gcm_version: "2.6.0"

# === Feature Toggles ===
install_docker: true
install_nodejs: true
install_claude_code: true
install_kubernetes_tools: true
install_screen_sessions: true
install_mcp_servers: true

# === Git Configuration ===
use_env_file: true
env_file_path: "{{ mcp_env_file }}"

# === Screen Session Configuration ===
screen_session_name: "{{ custom_session_name | default('KS') }}"
screen_logs_dir: "{{ logs_dir }}/screen"

# === Package Management ===
cache_valid_time: 3600
upgrade_packages: "safe"
autoremove_packages: true
remove_unused_packages: true

# === Essential packages ===
essential_packages:
  - curl
  - wget
  - vim
  - htop
  - git
  - unzip
  - python3-pip
  - jq
  - screen

# === Optional packages ===
optional_packages:
  - tree
  - ncdu
  - tmux