---
# Default variables for MCP role

# MCP configuration
mcp_config_dir: "{{ target_user_home }}/.claude"
mcp_config_file: "{{ mcp_config_dir }}/mcp-servers.json"
mcp_template_file: "mcp-servers.template.json"

# Environment file configuration
use_env_file: true
env_file_path: "{{ custom_env_file | default(playbook_dir + '/../.env') }}"
mcp_servers_file: "{{ custom_mcp_servers_file | default(playbook_dir + '/../mcp-servers.json') }}"

# claude-code-mcp-management tool configuration - use hidden deployment directory
mcp_management_dir: "{{ tools_dir }}/claude-code-mcp-management"
mcp_scope: "user"  # Can be 'user' or 'project'
mcp_project_path: "."  # Only used when scope is 'project'

# MCP server package installation (deprecated - now handled by claude-code-mcp-management)
# These are kept for reference but not used in the new implementation
install_mcp_packages: false
mcp_packages: []

# Docker configuration for MCP servers (deprecated - now handled by claude-code-mcp-management)
# These are kept for reference but not used in the new implementation
pull_docker_images: false
mcp_docker_images: []

# Validation settings
validate_mcp_config: true
create_backup: true

# Claude Code configuration location detection
claude_config_locations:
  - "{{ target_user_home }}/.claude"
  - "{{ target_user_home }}/.config/claude-code"
  - "{{ target_user_home }}/.local/share/claude-code"

# Environment variables to include in MCP configuration
mcp_env_vars:
  - "BRAVE_API_KEY"
  - "TAVILY_API_KEY" 
  - "KAGI_API_KEY"
  - "PERPLEXITY_API_KEY"
  - "JINA_AI_API_KEY"
  - "UPSTASH_REDIS_REST_URL"
  - "UPSTASH_REDIS_REST_TOKEN"
  - "OPENAI_API_KEY"
  - "ANTHROPIC_API_KEY"