---
# Common role tasks - System preparation and essential packages

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: "{{ cache_valid_time }}"
  retries: 3
  delay: 5
  tags:
    - system
    - packages

- name: Upgrade existing packages
  apt:
    upgrade: "{{ upgrade_packages }}"
    update_cache: false
  when: upgrade_packages is defined and upgrade_packages != false
  retries: 2
  delay: 10
  tags:
    - system
    - packages
    - upgrade

- name: Install essential packages
  apt:
    name: "{{ essential_packages }}"
    state: present
    update_cache: false
  retries: 3
  delay: 10
  tags:
    - system
    - packages

- name: Install optional packages
  apt:
    name: "{{ optional_packages }}"
    state: present
  when: optional_packages is defined and optional_packages | length > 0
  tags:
    - system
    - packages
    - optional

- name: Get target user information
  getent:
    database: passwd
    key: "{{ target_user }}"
  register: target_user_info

- name: Create user directories for global npm packages
  file:
    path: "{{ target_user_info.ansible_facts.getent_passwd[target_user][4] }}/.npm-global"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'
  tags:
    - system
    - npm-prep

- name: Configure timezone
  timezone:
    name: "{{ timezone }}"
  when: configure_timezone
  tags:
    - system
    - timezone

- name: Remove unused packages
  apt:
    autoremove: true
  when: autoremove_packages
  tags:
    - cleanup

- name: Clean apt cache
  apt:
    autoclean: true
  when: remove_unused_packages
  tags:
    - cleanup

- name: Gather system facts for validation
  setup:
    gather_subset:
      - "!all"
      - "min"
      - "network"
      - "virtual"
  tags:
    - validation