---
galaxy_info:
  author: Claude Code VM Deployment
  description: Git repository management and automated cloning
  company: Anthropic
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - 11
        - 12
  galaxy_tags:
    - git
    - repositories
    - development
    - automation
    - deployment

dependencies:
  - role: git
    when: ensure_git_installed | default(true)