---
# Global variables for all hosts in production environment

# System configuration
target_user: ksamaschke
debian_version: bookworm

# Docker configuration
docker_users:
  - ksamaschke
docker_install_compose: true
docker_compose_version: "latest"

# Node.js configuration
nodejs_version: "22"  # LTS version
nodejs_install_method: "nodesource"  # or "nvm"
nodejs_npm_global_packages:
  - "@anthropic-ai/claude-code"

# Package repositories
nodejs_repository: "https://deb.nodesource.com/node_{{ nodejs_version }}.x"
docker_repository: "https://download.docker.com/linux/debian"

# Git configuration
install_git_credential_manager: true
install_git_credential_oauth: false
generate_ssh_keys: true
git_user_name: ""  # Will be read from .env file or configure manually
git_user_email: ""  # Will be read from .env file or configure manually

# Personal Access Token configuration
use_env_file: true
env_file_required: false  # Set to true to require .env file
configure_pats: true
configure_git_signing: false
enable_ssh_url_conversion: false

# Kubernetes tools configuration
install_kubectl: true
install_kind: true
install_kompose: true
install_bash_completion: true
kubernetes_version: "v1.33"
kind_version: "v0.29.0"
kompose_version: "v1.36.0"

# Service management
services_to_enable:
  - docker
  - containerd

# Security settings
disable_ipv6: false
update_cache: true
upgrade_packages: true