---
# Default variables for common role

# System update settings
update_cache: true
upgrade_packages: safe
cache_valid_time: 3600

# Essential packages to install
essential_packages:
  - curl
  - wget
  - gnupg
  - lsb-release
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - build-essential
  - git
  - unzip
  - python3-pip
  - jq

# Optional packages
optional_packages:
  - htop
  - tree
  - vim

# System configuration
configure_timezone: false
timezone: "UTC"

# Cleanup settings
remove_unused_packages: true
autoremove_packages: true

# Package manager lock settings
package_manager_max_wait_seconds: 60  # Maximum time to wait for package manager locks
package_manager_check_interval: 2     # Seconds between lock checks

# Directory settings - use hidden deployment directory (fallback defaults)
deployment_base_dir: "{{ custom_deployment_dir | default('/home/' + target_user + '/.claude-code-vm') }}"
scripts_dir: "{{ deployment_base_dir }}/scripts"
screen_logs_dir: "{{ deployment_base_dir }}/logs/screen"

# Screen session configuration  
screen_session_name: "{{ custom_session_name | default('DEV') }}"