---
# Production inventory for Debian VM deployment
# This is an EXAMPLE inventory - use dynamic inventory generation instead
# To deploy: make deploy VM_HOST=your.ip TARGET_USER=username
#
# This file should NOT be used directly. The Makefile creates dynamic inventories
# based on provided VM_HOST and TARGET_USER parameters.

all:
  children:
    debian_servers:
      hosts:
        debian-vm:
          ansible_host: "YOUR_VM_IP_HERE"
          ansible_user: YOUR_USERNAME_HERE
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_become: yes
          ansible_become_method: sudo
          ansible_python_interpreter: /usr/bin/python3
          target_user: YOUR_TARGET_USER_HERE