---
# Production inventory for Debian VM deployment
# This is an EXAMPLE inventory - use main inventory.yml for actual deployments
# To deploy: make deploy VM_HOST=your.ip TARGET_USER=username

all:
  children:
    debian_servers:
      hosts:
        debian-vm:
          ansible_host: "192.168.1.113"
          ansible_user: ksamaschke
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_become: yes
          ansible_become_method: sudo
          ansible_python_interpreter: /usr/bin/python3
          target_user: ksamaschke