---
galaxy_info:
  author: Ansible Debian Stack
  description: Configure Model Context Protocol (MCP) servers for Claude Code
  company: Open Source
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
    - name: Ubuntu
      versions:
        - "20.04"
        - "22.04"
        - "24.04"
  galaxy_tags:
    - mcp
    - claude
    - ai
    - development
    - tools

dependencies:
  - role: nodejs
  - role: claude-code