---
# Main site playbook - Deploy full stack to Debian VM
# Installs Docker, Docker Compose, Node.js, and Claude Code

# Import external dependencies playbook first
- import_playbook: download-dependencies.yml

- name: Deploy Development Stack to Debian VM
  hosts: debian_servers
  become: true
  gather_facts: true
  serial: 1

  vars:
    deployment_timestamp: "{{ ansible_date_time.iso8601 }}"
    deployment_user: "{{ ansible_user }}"

  pre_tasks:
    - name: Display deployment information
      debug:
        msg:
          - "=== Ansible Deployment Started ==="
          - "Target Host: {{ inventory_hostname }} ({{ ansible_host }})"
          - "Operating System: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Architecture: {{ ansible_architecture }}"
          - "Deployment Time: {{ deployment_timestamp }}"
          - "Deployment User: {{ deployment_user }}"
          - "Target User: {{ target_user }}"
      tags: always

    - name: Verify SSH connectivity and sudo access
      ping:
      tags: always

    - name: Check sudo access
      command: sudo -n true
      register: sudo_check
      failed_when: sudo_check.rc != 0
      changed_when: false
      tags: always


  roles:
    - role: common
      tags: 
        - common
        - system
        - prerequisites

    - role: git
      tags:
        - git
        - credentials
        - version-control

    - role: geerlingguy.docker
      when: install_docker | default(false) | bool
      tags:
        - docker
        - containers
      vars:
        docker_users: ["{{ target_user }}"]

    - role: nodejs
      tags:
        - nodejs
        - npm
        - javascript
      vars:
        npm_global_packages: "{{ nodejs_npm_global_packages | default([]) }}"

    # Claude Code is installed via npm in the nodejs role
    # The claude-code role reference can be removed or used for additional configuration

    - role: kubernetes
      when: install_kubectl | default(false) | bool or install_kind | default(false) | bool or install_kompose | default(false) | bool
      tags:
        - kubernetes
        - kubectl
        - kind
        - kompose
        - k8s
        - bash-completion

    - role: mcp
      tags:
        - mcp
        - model-context-protocol
        - claude-code-mcp
        - ai

  post_tasks:
    - name: Ensure /tmp permissions are correct after all installations
      shell: |
        current_perms=$(stat -c "%a" /tmp)
        if [ "$current_perms" != "1777" ]; then
          echo "FIXING: /tmp permissions were $current_perms, setting to 1777"
          chmod 1777 /tmp
          chown root:root /tmp
          echo "FIXED: /tmp permissions now correct"
        else
          echo "OK: /tmp permissions are correct (1777)"
        fi
      become: true
      register: final_tmp_fix
      changed_when: "'FIXING:' in final_tmp_fix.stdout"
      tags: always

    - name: Display /tmp fix status
      debug:
        msg: "{{ final_tmp_fix.stdout_lines }}"
      tags: always

    - name: Final system information
      debug:
        msg:
          - "=== Deployment Summary ==="
          - "Docker Version: {{ docker_version.stdout | default('Not captured') }}"
          - "Docker Compose Version: {{ docker_compose_version.stdout | default('Not captured') }}"
          - "Node.js Version: {{ nodejs_version_check.stdout | default('Not captured') }}"
          - "npm Version: {{ npm_version_check.stdout | default('Not captured') }}"
          - "Claude Code Version: {{ claude_version_check.stdout | default('Not captured') }}"
          - "Deployment completed at: {{ ansible_date_time.iso8601 }}"
      tags: always

    - name: Display post-deployment instructions
      debug:
        msg:
          - "=== Post-Deployment Instructions ==="
          - "1. Log out and log back in for Docker group membership to take effect"
          - "2. Run 'source ~/.bashrc' to update PATH for npm global packages"
          - "3. Verify installations:"
          - "   - docker --version"
          - "   - docker compose version"
          - "   - node --version"
          - "   - npm --version"
          - "   - claude --version"
          - "4. To use Docker without sudo, start a new shell session"
          - "5. To use Claude Code, run 'claude' and follow authentication prompts"
      tags: always

  handlers:
    - name: restart docker
      systemd:
        name: docker
        state: restarted
        daemon_reload: true