---
# Node.js role tasks - Install Node.js via official NodeSource repository

- name: Check if Node.js is already installed
  command: node --version
  register: nodejs_version_check
  failed_when: false
  changed_when: false
  tags:
    - nodejs
    - check

- name: Check if npm is already installed
  command: npm --version
  register: npm_version_check
  failed_when: false
  changed_when: false
  tags:
    - nodejs
    - check

- name: Set Node.js version facts
  set_fact:
    nodejs_installed: "{{ nodejs_version_check.rc == 0 }}"
    nodejs_current_version: "{{ nodejs_version_check.stdout | default('none') }}"
    nodejs_target_version: "{{ nodejs_version | default('22') }}"
  tags:
    - nodejs

- name: Install required packages
  apt:
    name:
      - curl
      - python3-debian
      - gnupg
    state: present
    update_cache: true
  when: not nodejs_installed or nodejs_current_version is version('v' + nodejs_target_version, '<')
  tags:
    - nodejs
    - prerequisites

- name: Download Node.js setup script
  get_url:
    url: "https://deb.nodesource.com/setup_{{ nodejs_target_version }}.x"
    dest: "/tmp/nodesource_setup.sh"
    mode: '0755'
    timeout: "{{ download_timeout | default(30) }}"
  when: not nodejs_installed or nodejs_current_version is version('v' + nodejs_target_version, '<')
  retries: "{{ nodejs_install_retries | default(3) }}"
  delay: "{{ nodejs_install_delay | default(10) }}"
  become: true
  tags:
    - nodejs

- name: Set up Node.js repository
  shell: bash /tmp/nodesource_setup.sh
  when: not nodejs_installed or nodejs_current_version is version('v' + nodejs_target_version, '<')
  become: true
  tags:
    - nodejs

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: true
  when: not nodejs_installed or nodejs_current_version is version('v' + nodejs_target_version, '<')
  retries: "{{ nodejs_install_retries | default(3) }}"
  delay: "{{ nodejs_install_delay | default(10) }}"
  until: nodejs_installation is succeeded
  register: nodejs_installation
  tags:
    - nodejs
    - packages

- name: Remove setup script
  file:
    path: /tmp/nodesource_setup.sh
    state: absent
  tags:
    - nodejs
    - cleanup

- name: Set npm global directory path
  set_fact:
    npm_config_prefix: "{{ target_user_home }}/.npm-global"

- name: Create npm global directory for user
  file:
    path: "{{ npm_config_prefix }}"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'
  when: configure_npm_for_user
  tags:
    - nodejs
    - npm
    - configuration

- name: Configure npm prefix for user
  shell: npm config set prefix '{{ npm_config_prefix }}'
  become_user: "{{ target_user }}"
  when: configure_npm_for_user
  tags:
    - nodejs
    - npm
    - configuration

- name: Add npm global bin to PATH in .bashrc
  lineinfile:
    path: "{{ target_user_home }}/.bashrc"
    line: 'export PATH={{ npm_config_prefix }}/bin:$PATH'
    create: true
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
  when: configure_npm_for_user
  tags:
    - nodejs

- name: Source .bashrc to update PATH immediately for validation
  shell: |
    source {{ target_user_home }}/.bashrc
    echo "PATH updated: $PATH"
  become_user: "{{ target_user }}"
  when: configure_npm_for_user
  register: path_update
  tags:
    - nodejs
    - path

- name: Create environment setup script for immediate use
  copy:
    content: |
      #!/bin/bash
      export PATH={{ npm_config_prefix }}/bin:$PATH
      export NODE_PATH={{ npm_config_prefix }}/lib/node_modules
    dest: /etc/profile.d/npm-global.sh
    mode: '0644'
  become: true
  when: configure_npm_for_user
  tags:
    - nodejs
    - environment
    - npm
    - configuration

- name: Update npm to latest version
  shell: npm install -g npm@latest
  become_user: "{{ target_user }}"
  environment:
    PATH: "{{ npm_config_prefix }}/bin:{{ ansible_env.PATH }}"
  when: update_npm_to_latest and npm_config_prefix is defined
  tags:
    - nodejs
    - npm
    - update

- name: Debug npm_global_packages variable
  debug:
    msg: 
      - "npm_global_packages: {{ npm_global_packages | default('NOT SET') }}"
      - "npm_global_packages length: {{ npm_global_packages | length | default(0) }}"
      - "npm_config_prefix: {{ npm_config_prefix | default('NOT SET') }}"
  tags:
    - nodejs
    - npm
    - packages

- name: Install global npm packages
  npm:
    name: "{{ item }}"
    global: true
    executable: "{{ npm_config_prefix }}/bin/npm"
  become_user: "{{ target_user }}"
  environment:
    PATH: "{{ npm_config_prefix }}/bin:{{ ansible_env.PATH }}"
  loop: "{{ npm_global_packages }}"
  when: npm_global_packages is defined and npm_global_packages | length > 0 and npm_config_prefix is defined
  tags:
    - nodejs
    - npm
    - packages

- name: Validate Node.js installation
  block:
    - name: Check Node.js version
      command: node --version
      register: nodejs_version_check
      changed_when: false

    - name: Check npm version
      command: npm --version
      register: npm_version_check
      changed_when: false

    - name: Display Node.js and npm versions
      debug:
        msg: 
          - "Node.js: {{ nodejs_version_check.stdout }}"
          - "npm: {{ npm_version_check.stdout }}"

    - name: Verify npm global configuration
      command: npm config get prefix
      register: npm_prefix_check
      become_user: "{{ target_user }}"
      changed_when: false
      when: configure_npm_for_user

    - name: Display npm prefix configuration
      debug:
        msg: "npm prefix: {{ npm_prefix_check.stdout }}"
      when: configure_npm_for_user and npm_prefix_check is defined

    - name: Test npm package installation (optional)
      npm:
        name: "cowsay"
        global: true
        executable: "{{ npm_config_prefix }}/bin/npm"
      become_user: "{{ target_user }}"
      environment:
        PATH: "{{ npm_config_prefix }}/bin:{{ ansible_env.PATH }}"
      register: npm_test_install
      when: test_npm_install

    - name: Remove test package
      npm:
        name: "cowsay"
        global: true
        state: absent
        executable: "{{ npm_config_prefix }}/bin/npm"
      become_user: "{{ target_user }}"
      environment:
        PATH: "{{ npm_config_prefix }}/bin:{{ ansible_env.PATH }}"
      when: test_npm_install and npm_test_install is succeeded

  when: validate_installation
  tags:
    - nodejs
    - validation