---
# MCP (Model Context Protocol) server configuration tasks

- name: Get target user information
  getent:
    database: passwd
    key: "{{ target_user }}"
  register: mcp_user_info
  tags:
    - mcp
    - prerequisites

- name: Set target user home directory
  set_fact:
    target_user_home: "{{ mcp_user_info.ansible_facts.getent_passwd[target_user][4] }}"
  tags:
    - mcp
    - prerequisites

- name: Load environment variables from .env file
  block:
    - name: Check if .env file exists
      stat:
        path: "{{ env_file_path }}"
      register: env_file_stat
      delegate_to: localhost
      become: false
      run_once: true

    - name: Read .env file
      slurp:
        src: "{{ env_file_path }}"
      register: env_file_content
      delegate_to: localhost
      become: false
      run_once: true
      when: env_file_stat.stat.exists

    - name: Parse environment variables
      set_fact:
        env_vars: "{{ env_vars | default({}) | combine({item.split('=')[0]: item.split('=')[1] | regex_replace('^\"|\"$', '')}) }}"
      loop: "{{ (env_file_content.content | b64decode).split('\n') }}"
      when: 
        - env_file_stat.stat.exists
        - item is match('^[A-Z_]+=.*')
        - not item.startswith('#')
      no_log: true

    - name: Display loaded environment variables (masked)
      debug:
        msg: "Loaded {{ env_vars.keys() | list | length }} environment variables from .env file"
      when: env_file_stat.stat.exists
  when: use_env_file
  tags:
    - mcp
    - env-file

# MCP server dependencies are already handled by other roles
# No need to install Ansible on the target machine

- name: Configure MCP servers using claude-code-mcp-management
  block:
    - name: Check if Claude Code is installed and accessible
      shell: "bash -c 'source ~/.bashrc && source /etc/profile.d/npm-global.sh && claude --version'"
      become_user: "{{ target_user }}"
      register: claude_check
      changed_when: false

    - name: Check if local mcp-servers.json exists
      stat:
        path: "{{ mcp_servers_file }}"
      register: local_mcp_config_exists
      delegate_to: localhost
      become: false

    - name: Generate default MCP servers configuration if none exists locally
      template:
        src: mcp-servers.json.j2
        dest: "{{ mcp_servers_file }}"
        mode: '0600'
      delegate_to: localhost
      become: false
      when: not local_mcp_config_exists.stat.exists

    - name: Synchronize MCP servers using remote configuration tool
      shell: |
        cd {{ playbook_dir }}/../.external-tools/claude-code-mcp-management-main && \
        make sync-remote \
          CONFIG_FILE="{{ mcp_servers_file }}" \
          ENV_FILE="{{ env_file_path }}" \
          SSH_HOST="{{ ansible_host }}" \
          SSH_USER="{{ target_user }}"
      delegate_to: localhost
      become: false
      register: mcp_sync_result
      args:
        executable: /bin/bash

    - name: Display MCP synchronization status
      debug:
        msg: 
          - "=== MCP Synchronization Status ==="
          - "Sync command executed successfully"
      when: mcp_sync_result is defined

    - name: Display MCP synchronization results
      debug:
        msg:
          - "=== MCP Server Synchronization ==="
          - "{{ mcp_sync_result.stdout_lines | default(['No output']) }}"
      when: mcp_sync_result.stdout_lines is defined

    - name: Show MCP configuration status
      debug:
        msg:
          - "=== MCP Server Configuration Status ==="
          - "MCP servers have been configured for Claude Code on {{ target_user }}@{{ ansible_host }}"
          - "Configuration applied from: {{ mcp_servers_file }}"
          - "Environment variables loaded from: {{ env_file_path }}"

  tags:
    - mcp
    - config

- name: Display MCP setup completion
  debug:
    msg:
      - "=== MCP Server Configuration Complete ==="
      - "Target host: {{ target_user }}@{{ ansible_host }}"
      - "Environment variables loaded: {{ env_vars.keys() | list | length if env_vars is defined else 0 }}"
      - "Configuration file: {{ mcp_servers_file }}"
      - "Environment file: {{ env_file_path }}"
      - ""
      - "Claude Code on the target VM has been configured with the specified MCP servers."
      - "The user can now use Claude Code with the configured MCP servers."
  tags:
    - mcp
    - completion