---
# Role metadata for nodejs role

galaxy_info:
  role_name: nodejs
  author: Ansible Automation
  description: Install Node.js LTS via NodeSource repository on Debian systems
  company: N/A
  license: MIT
  min_ansible_version: "2.10"
  
  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
        - buster
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble

  galaxy_tags:
    - nodejs
    - npm
    - javascript
    - debian
    - ubuntu
    - development

dependencies: []