---
# Default variables for MCP role

# MCP configuration
mcp_config_dir: "{{ target_user_home }}/.claude"
mcp_config_file: "{{ mcp_config_dir }}/mcp-servers.json"
mcp_template_file: "mcp-servers.template.json"

# Environment file configuration
use_env_file: true
env_file_path: "{{ playbook_dir }}/.env"

# MCP server package installation
install_mcp_packages: true
mcp_packages:
  - "@modelcontextprotocol/server-sequential-thinking"
  - "@modelcontextprotocol/server-memory"
  - "@modelcontextprotocol/server-brave-search"
  - "@upstash/context7-mcp"
  - "@cablate/mcp-doc-forge"
  - "mcp-omnisearch"

# Docker configuration for MCP servers
pull_docker_images: true
mcp_docker_images:
  - "mcp/puppeteer"

# Validation settings
validate_mcp_config: true
create_backup: true

# Claude Code configuration location detection
claude_config_locations:
  - "{{ target_user_home }}/.claude"
  - "{{ target_user_home }}/.config/claude-code"
  - "{{ target_user_home }}/.local/share/claude-code"

# Environment variables to include in MCP configuration
mcp_env_vars:
  - "BRAVE_API_KEY"
  - "TAVILY_API_KEY" 
  - "KAGI_API_KEY"
  - "PERPLEXITY_API_KEY"
  - "JINA_AI_API_KEY"
  - "UPSTASH_REDIS_REST_URL"
  - "UPSTASH_REDIS_REST_TOKEN"
  - "OPENAI_API_KEY"
  - "ANTHROPIC_API_KEY"