---
# Production inventory for Debian VM deployment
# Target: 192.168.1.111 with user ksamaschke (Debian 12.11 Bookworm)

all:
  children:
    debian_servers:
      hosts:
        debian-vm:
          ansible_host: 192.168.1.111
          ansible_user: ksamaschke
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_become: yes
          ansible_become_method: sudo
          ansible_python_interpreter: /usr/bin/python3